---
name: "test push"
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
        path: repo
    
    - uses: actions/checkout@v3
      with:
        repository: Burakhan/test2
        fetch-depth: 0
        path: test2

    - name: Change dir
      run: |
        [ -d  test2/test1 ] && rm -rf test2/test1
        mkdir test2/test1
        cp -r repo/build test2/test1
        ls  -al repo
        ls  -al test2
        ls -al test2/test1

    - name: Commit files
      run: |
        cd test2
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git add test1/
        git commit -m "Add changes" -a
      
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        ssh: true
        github_token: ${{ secrets.REPO_TOKEN }}
        force_with_lease: true
        directory: test2